export default {
  id: "bedroom-master",
  name: "Bedroom Master",
  icon: "🛏️",
  items: [
    { id: "master-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "master-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "master-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "master-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "master-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "master-plan-window-measure", type: "plan", text: "Measure window width and height accurately" },
    { id: "master-plan-curtain-drop", type: "plan", text: "Decide curtain drop: to sill, below sill, or floor length" },
    { id: "master-plan-rod-extension", type: "plan", text: "Leave 15-25 cm rod extension on each side for full opening" },
    { id: "master-plan-wall-type", type: "plan", text: "Confirm wall type (masonry or plasterboard) for correct anchors" },
    { id: "master-plan-clearance", type: "plan", text: "Check for radiator/heater or furniture clearance under curtains" },
    { id: "master-buy-rod", type: "buy", text: "1 curtain rod" },
    { id: "master-buy-day-curtains", type: "buy", text: "2 light cotton curtains (sheer/day curtains)" },
    { id: "master-buy-blackout", type: "buy", text: "2 heavy dark curtains (blackout/night curtains)" },
    { id: "master-buy-curtain-hooks", type: "buy", text: "Curtain rings/hooks or eyelets (matching curtain type)" },
    { id: "master-buy-brackets", type: "buy", text: "2 or 3 wall brackets for rod support (based on rod length)" },
    { id: "master-buy-wall-plugs", type: "buy", text: "Wall plugs and screws suitable for wall type" },
    { id: "master-buy-finials", type: "buy", text: "Finials/end caps for curtain rod" },
    { id: "master-buy-bed", type: "buy", text: "Bed frame (mattress, duvet, and bedding to be reused from existing apartment)" },
    { id: "master-do-mark-bracket", type: "do", text: "Mark bracket height and keep both sides level" },
    { id: "master-do-drill-brackets", type: "do", text: "Drill holes and fix brackets securely" },
    { id: "master-do-install-rod", type: "do", text: "Install rod and check for level and stability" },
    { id: "master-do-hang-day", type: "do", text: "Hang light cotton curtains first" },
    { id: "master-do-hang-blackout", type: "do", text: "Hang heavy dark curtains and verify smooth sliding" },
    { id: "master-do-test-curtains", type: "do", text: "Test full open and close movement without floor dragging" },
    { id: "master-do-iron-curtains", type: "do", text: "Steam or iron curtains after hanging for final finish" },
  ],
};
