export default {
  id: "buanderie",
  name: "Buanderie",
  icon: "🧺",
  items: [
    { id: "buanderie-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-layout", type: "plan", text: "Confirm appliance layout and door clearances in Buanderie", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-services", type: "plan", text: "Check power sockets, water supply, and drain points for washing machine, drier, and freezer", tasks: ["provisional-acceptance"] },
    { id: "buanderie-plan-drier-stand", type: "plan", text: "Confirm load capacity and fixing method for stand mounting drier above washing machine" },
    { id: "buanderie-plan-shelves-measure", type: "plan", text: "Measure under-stairs storage area for shelves and cleaning product storage", tasks: ["furniture-making"] },
    { id: "buanderie-plan-shelf-spacing", type: "plan", text: "Plan shelf depth, height spacing, and access for detergent and cleaning supplies", tasks: ["furniture-making"] },
    { id: "buanderie-buy-freezer", type: "buy", text: "Freezer" },
    { id: "buanderie-buy-drier", type: "buy", text: "Drier" },
    { id: "buanderie-buy-drier-stand", type: "buy", text: "Stand to mount drier over washing machine" },
    { id: "buanderie-buy-shelves", type: "buy", text: "Shelves or shelf boards for under-stairs storage", tasks: ["furniture-making"] },
    { id: "buanderie-buy-brackets", type: "buy", text: "Wall brackets, anchors, and screws for shelf installation", tasks: ["furniture-making"] },
    { id: "buanderie-buy-storage-bins", type: "buy", text: "Storage bins or containers for detergents and cleaning supplies" },
    { id: "buanderie-do-measure-spaces", type: "do", text: "Measure final appliance spaces in Buanderie" },
    { id: "buanderie-do-order-appliances", type: "do", text: "Order freezer, drier, and mounting stand" },
    { id: "buanderie-do-mark-shelves", type: "do", text: "Measure and mark shelf positions under the stairs", tasks: ["furniture-making"] },
    { id: "buanderie-do-install-shelves", type: "do", text: "Install shelves under the stairs for cleaning products and detergent", tasks: ["furniture-making"] },
    { id: "buanderie-do-organize", type: "do", text: "Organize storage bins and supplies on the new shelves" },
    { id: "buanderie-do-drier-stand", type: "do", text: "Install stand above washing machine position" },
    { id: "buanderie-do-connect-drier", type: "do", text: "Install and connect drier" },
    { id: "buanderie-do-freezer", type: "do", text: "Install freezer and confirm ventilation clearance" },
    { id: "buanderie-do-paint-walls", type: "do", text: "Paint Buanderie walls", tasks: ["painting"] },
  ],
};
