export default {
  id: "dressing-room",
  name: "Dressing Room",
  icon: "👗",
  items: [
    { id: "dressing-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "dressing-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "dressing-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "dressing-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "dressing-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "dressing-plan-measurements", type: "plan", text: "Confirm final wall-to-wall and floor-to-ceiling measurements after plaster and paint", tasks: ["ikea-pax"] },
    { id: "dressing-plan-skirting-pax", type: "plan", text: "Check skirting/baseboard thickness against PAX and MDF layout", tasks: ["ikea-pax", "cloison"] },
    { id: "dressing-plan-door-clearance", type: "plan", text: "Confirm door swing and walking clearance in closet corridor", tasks: ["ikea-pax"] },
    { id: "dressing-plan-socket-heights", type: "plan", text: "Plan exact socket heights and positions before closing frames and MDF", tasks: ["ikea-pax", "cloison"] },
    { id: "dressing-plan-led-driver", type: "plan", text: "Plan LED driver location with future access for maintenance" },
    { id: "dressing-plan-led-route", type: "plan", text: "Confirm cable route for LED strips and ceiling lights" },
    { id: "dressing-plan-pax-doors", type: "plan", text: "Check IKEA for second-hand Försund PAX doors for sanding and Peacock Blue finish", tasks: ["ikea-pax"] },
    { id: "dressing-plan-paint-test", type: "plan", text: "Test Peacock Blue and corridor paint on sample boards in real light", tasks: ["painting"] },
    { id: "dressing-plan-primer-compat", type: "plan", text: "Confirm primer compatibility for walls, MDF, and furniture paint system", tasks: ["painting"] },
    { id: "dressing-buy-pax", type: "buy", text: "IKEA main PAX unit", tasks: ["ikea-pax"] },
    { id: "dressing-buy-mdf", type: "buy", text: "MDF sheets (18 mm and 6 mm where needed)", tasks: ["ikea-pax", "cloison"] },
    { id: "dressing-buy-beams", type: "buy", text: "Wooden beams 38×38 mm", tasks: ["ikea-pax"] },
    { id: "dressing-buy-sockets", type: "buy", text: "Power sockets and screw supports for hidden unit" },
    { id: "dressing-buy-handles", type: "buy", text: "Handles", tasks: ["ikea-pax"] },
    { id: "dressing-buy-copper-paint", type: "buy", text: "Metal copper paint", tasks: ["painting"] },
    { id: "dressing-buy-peacock-blue", type: "buy", text: "Door paint – Peacock Blue (furniture paint, for Försund PAX doors)", tasks: ["painting"] },
    { id: "dressing-buy-door-mdf-primer", type: "buy", text: "Primer for PAX doors and MDF surfaces (confirm compatibility with Peacock Blue paint)", tasks: ["painting"] },
    { id: "dressing-buy-mdf-paint", type: "buy", text: "MDF paint to match wall style (hidden surfaces inside closet)", tasks: ["painting"] },
    { id: "dressing-buy-tiefgrund-dressing", type: "buy", text: "Tiefgrund LF primer for dressing room walls (if walls will be visible before MDF closure)", tasks: ["painting"] },
    { id: "dressing-buy-led-adapter", type: "buy", text: "LED adapter for strip lights with door proximity sensor" },
    { id: "dressing-buy-ceiling-lights", type: "buy", text: "Ceiling lights" },
    { id: "dressing-buy-carpet-cutter", type: "buy", text: "Carpet cutter (type to be determined)" },
    { id: "dressing-buy-carpet", type: "buy", text: "Carpet setup materials" },
    { id: "dressing-buy-led-drivers", type: "buy", text: "LED drivers" },
    { id: "dressing-buy-wall-anchors", type: "buy", text: "Wall anchors and screws by wall type", tasks: ["ikea-pax"] },
    { id: "dressing-buy-filler", type: "buy", text: "Filler and caulk" },
    { id: "dressing-buy-level", type: "buy", text: "Laser level or long spirit level" },
    { id: "dressing-do-pax-layout", type: "do", text: "Build and design IKEA PAX layout", tasks: ["ikea-pax"] },
    { id: "dressing-do-ikea-visit", type: "do", text: "Visit IKEA to check second-hand PAX units and doors", tasks: ["ikea-pax"] },
    { id: "dressing-do-order-pax", type: "do", text: "Order the PAX unit and arrange transport or home delivery", tasks: ["ikea-pax"] },
    { id: "dressing-do-prime-walls", type: "do", text: "Prime dressing room walls", tasks: ["painting"] },
    { id: "dressing-do-paint-ceiling", type: "do", text: "Paint dressing room ceiling", tasks: ["painting"] },
    { id: "dressing-do-paint-walls", type: "do", text: "Paint dressing room walls", tasks: ["painting"] },
    { id: "dressing-do-sockets-access", type: "do", text: "Provide access to power sockets" },
    { id: "dressing-do-support-frames", type: "do", text: "Build support frames where necessary", tasks: ["ikea-pax"] },
    { id: "dressing-do-assemble-pax", type: "do", text: "Assemble PAX units after delivery", tasks: ["ikea-pax"] },
    { id: "dressing-do-fix-pax", type: "do", text: "Level and fix PAX units safely to the wall", tasks: ["ikea-pax"] },
    { id: "dressing-do-mdf-covers", type: "do", text: "Apply MDF covers", tasks: ["ikea-pax", "cloison"] },
    { id: "dressing-do-sand-doors", type: "do", text: "Sand PAX doors", tasks: ["ikea-pax", "painting"] },
    { id: "dressing-do-paint-doors", type: "do", text: "Paint PAX doors and exposed MDF inside closet", tasks: ["painting"] },
    { id: "dressing-do-paint-corridor", type: "do", text: "Paint closet corridor to match wall paint (non-furniture paint)", tasks: ["painting"] },
    { id: "dressing-do-carpet", type: "do", text: "Cut existing green carpet to closet shape" },
    { id: "dressing-do-align-doors", type: "do", text: "Fix and align doors", tasks: ["ikea-pax"] },
    { id: "dressing-do-socket-access", type: "do", text: "Create an access point for hidden sockets and LED adapter" },
    { id: "dressing-do-led", type: "do", text: "Install LED lights with door proximity sensors" },
    { id: "dressing-do-handles", type: "do", text: "Install handles using a drilling template", tasks: ["ikea-pax"] },
  ],
};
