export default {
  id: "greenhouse",
  name: "Greenhouse",
  icon: "🌿",
  items: [
    { id: "greenhouse-plan-base", type: "plan", text: "Check whether the greenhouse needs a base, slab, or anchor kit" },
    { id: "greenhouse-plan-location", type: "plan", text: "Confirm the chosen location has enough sun and access around all sides" },
    { id: "greenhouse-plan-drainage", type: "plan", text: "Check drainage and water runoff around the installation area" },
    { id: "greenhouse-plan-wind", type: "plan", text: "Check wind exposure and anchoring requirements" },
    { id: "greenhouse-plan-ventilation", type: "plan", text: "Confirm ventilation and shading needs for summer use" },
    { id: "greenhouse-plan-model-research", type: "plan", text: "Research and identify the right greenhouse model based on available space and needs" },
    { id: "greenhouse-buy-greenhouse", type: "buy", group: "Garden & Outdoor", text: "Greenhouse with anchoring/base materials" },
    { id: "greenhouse-buy-ladder", type: "buy", group: "Tools & Safety", text: "Get a taller ladder" },
    { id: "greenhouse-buy-tools", type: "buy", group: "Tools & Safety", text: "Buy or gather required installation tools" },
    { id: "greenhouse-buy-ventilation", type: "buy", group: "Garden & Outdoor", text: "Ventilation or shading accessories if needed" },
    { id: "greenhouse-do-spot", type: "do", text: "Identify the right spot for installation" },
    { id: "greenhouse-do-order-greenhouse", type: "do", text: "Order the greenhouse (after model selection and power verification)" },
    { id: "greenhouse-do-power-check", type: "do", text: "Verify power source requirements with Gaetan and check where the garden power line currently ends" },
    { id: "greenhouse-do-prepare-base", type: "do", text: "Prepare and level the base area" },
    { id: "greenhouse-do-install", type: "do", text: "Install the greenhouse following instructions or schedule installers" },
    { id: "greenhouse-do-check", type: "do", text: "Check doors, vents, and fixings after installation" },
  ],
};
