export default {
  id: "grenier",
  name: "Grenier",
  icon: "🏠",
  items: [
    { id: "grenier-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-measure-walls", type: "plan", text: "Measure full grenier wall and ceiling areas for plasterboard quantity", tasks: ["cloison"] },
    { id: "grenier-plan-profile-grid", type: "plan", text: "Define aluminum profile grid layout and fixing points", tasks: ["cloison"] },
    { id: "grenier-plan-light-positions", type: "plan", text: "Confirm light fixture slot positions before closing plasterboard", tasks: ["cloison"] },
    { id: "grenier-plan-socket-routes", type: "plan", text: "Confirm socket positions and cable routes before wall closure", tasks: ["cloison"] },
    { id: "grenier-plan-floor-level", type: "plan", text: "Check floor level and plan parquet orientation", tasks: ["flooring"] },
    { id: "grenier-plan-office-layout", type: "plan", text: "Plan grenier office layout (desk, chair, storage for office work setup)" },
    { id: "grenier-plan-wifi-signal", type: "plan", text: "Assess WiFi signal coverage from main router or plan for WiFi extender" },
    { id: "grenier-buy-alu-profiles", type: "buy", text: "Aluminum profiles for plasterboard framing", tasks: ["cloison"] },
    { id: "grenier-buy-plasterboard", type: "buy", text: "Plasterboards for grenier walls/ceiling", tasks: ["cloison"] },
    { id: "grenier-buy-plaster-paste", type: "buy", text: "Plaster paste / joint compound", tasks: ["cloison"] },
    { id: "grenier-buy-pb-primer", type: "buy", text: "Primer for plasterboard", tasks: ["cloison"] },
    { id: "grenier-buy-pvc-panels", type: "buy", text: "PVC wall panels", tasks: ["wall-panels"] },
    { id: "grenier-buy-panel-glue", type: "buy", text: "Glue for PVC panels", tasks: ["wall-panels"] },
    { id: "grenier-buy-parquet", type: "buy", text: "Parquet flooring", tasks: ["flooring"] },
    { id: "grenier-buy-underlayer", type: "buy", text: "8 mm underlayer for parquet", tasks: ["flooring"] },
    { id: "grenier-buy-light-slots", type: "buy", text: "Light fixture slots / recessed fixture housings", tasks: ["cloison"] },
    { id: "grenier-buy-elec-boxes", type: "buy", text: "Power sockets, switch plates, and electrical boxes" },
    { id: "grenier-buy-filler-caulk", type: "buy", text: "Filler and caulk for joints and edges", tasks: ["cloison"] },
    { id: "grenier-buy-junction-acc", type: "buy", text: "Junction accessories" },
    { id: "grenier-buy-bulbs", type: "buy", text: "Bulbs for light fixtures" },
    { id: "grenier-buy-working-tables", type: "buy", text: "2 working tables" },
    { id: "grenier-buy-working-chairs", type: "buy", text: "2 working chairs" },
    { id: "grenier-buy-desk", type: "buy", text: "Desk for office work" },
    { id: "grenier-buy-office-chair", type: "buy", text: "Office chair for desk" },
    { id: "grenier-buy-office-storage", type: "buy", text: "Office storage (shelves or filing cabinet)" },
    { id: "grenier-buy-ceiling-lights-grenier", type: "buy", text: "Ceiling lights for office (consistent with house pattern)" },
    { id: "grenier-buy-screws-anchors", type: "buy", text: "Screws, anchors, and profile connectors", tasks: ["cloison"] },
    { id: "grenier-do-install-profiles", type: "do", text: "Install aluminum profile framework", tasks: ["cloison"] },
    { id: "grenier-do-route-wiring", type: "do", text: "Route electrical wiring for sockets and light fixtures", tasks: ["cloison"] },
    { id: "grenier-do-install-plasterboard", type: "do", text: "Install plasterboards on profile framework", tasks: ["cloison"] },
    { id: "grenier-do-plaster-joints", type: "do", text: "Apply plaster paste and finish joints", tasks: ["cloison"] },
    { id: "grenier-do-prime-pb", type: "do", text: "Apply primer on plasterboard surfaces", tasks: ["cloison"] },
    { id: "grenier-do-pvc-panels", type: "do", text: "Mount PVC wall panels on primed plasterboard using panel glue", tasks: ["wall-panels"] },
    { id: "grenier-do-sockets", type: "do", text: "Install and connect power sockets" },
    { id: "grenier-do-light-fixtures", type: "do", text: "Install light fixture slots and fit light fixtures", tasks: ["cloison"] },
    { id: "grenier-do-parquet", type: "do", text: "Lay 8 mm underlayer and install parquet flooring", tasks: ["flooring"] },
    { id: "grenier-do-finishing", type: "do", text: "Final finishing, sealants, and cleanup" },
  ],
};
