export default {
  id: "grenier",
  name: "Grenier",
  icon: "🏠",
  items: [
    { id: "grenier-plan-check-walls", type: "plan", text: "Walls and ceiling are plastered, smooth, and ready for primer and paint", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-doors", type: "plan", text: "Grenier door opens, closes, and latches correctly", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-measure-walls", type: "plan", text: "Measure grenier wall and ceiling areas for primer and paint quantities", tasks: ["painting"] },
    { id: "grenier-plan-profile-grid", type: "plan", text: "Inspect sprayed foam insulation under the ceiling for complete and even coverage", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-light-positions", type: "plan", text: "Confirm Velux opens, closes, and seals correctly with no condensation traces", tasks: ["provisional-acceptance"] },
    { id: "grenier-plan-socket-routes", type: "plan", text: "Confirm socket positions and lighting points for planned office layout" },
    { id: "grenier-plan-floor-level", type: "plan", text: "Check floor level and plan parquet orientation", tasks: ["flooring"] },
    { id: "grenier-plan-office-layout", type: "plan", text: "Plan grenier office layout (desk, chair, storage for office work setup)" },
    { id: "grenier-plan-wifi-signal", type: "plan", text: "Assess WiFi signal coverage from main router or plan for WiFi extender" },
    { id: "grenier-buy-alu-profiles", type: "buy", group: "Paint", text: "Filler for small plaster defects before painting", tasks: ["painting"] },
    { id: "grenier-buy-plasterboard", type: "buy", group: "Paint", text: "Wall and ceiling paint for grenier office finishing", tasks: ["painting"] },
    { id: "grenier-buy-plaster-paste", type: "buy", group: "Paint", text: "Joint compound for small repairs and touch-ups", tasks: ["painting"] },
    { id: "grenier-buy-pb-primer", type: "buy", group: "Paint", text: "Primer suitable for plastered walls and ceilings", tasks: ["painting"] },
    { id: "grenier-buy-pvc-panels", type: "buy", group: "Furniture Store", text: "PVC wall panels", tasks: ["wall-panels"] },
    { id: "grenier-buy-panel-glue", type: "buy", group: "Furniture Store", text: "Glue for PVC panels", tasks: ["wall-panels"] },
    { id: "grenier-buy-parquet", type: "buy", group: "Textiles & Decor", text: "Parquet flooring", tasks: ["flooring"] },
    { id: "grenier-buy-underlayer", type: "buy", group: "Textiles & Decor", text: "8 mm underlayer for parquet", tasks: ["flooring"] },
    { id: "grenier-buy-light-slots", type: "buy", group: "Electricals", text: "Light fixture slots / recessed fixture housings", tasks: ["cloison"] },
    { id: "grenier-buy-elec-boxes", type: "buy", group: "Electricals", text: "Power sockets, switch plates, and electrical boxes" },
    { id: "grenier-buy-filler-caulk", type: "buy", group: "Paint", text: "Filler and caulk for joints and edges", tasks: ["cloison"] },
    { id: "grenier-buy-junction-acc", type: "buy", group: "Electricals", text: "Junction accessories" },
    { id: "grenier-buy-bulbs", type: "buy", group: "Electricals", text: "Bulbs for light fixtures" },
    { id: "grenier-buy-working-tables", type: "buy", group: "Office", text: "2 working tables" },
    { id: "grenier-buy-working-chairs", type: "buy", group: "Office", text: "2 working chairs" },
    { id: "grenier-buy-desk", type: "buy", group: "Office", text: "Desk for office work" },
    { id: "grenier-buy-office-chair", type: "buy", group: "Office", text: "Office chair for desk" },
    { id: "grenier-buy-office-storage", type: "buy", group: "Office", text: "Office storage (shelves or filing cabinet)" },
    { id: "grenier-buy-ceiling-lights-grenier", type: "buy", group: "Electricals", text: "Ceiling lights for office (consistent with house pattern)" },
    { id: "grenier-buy-screws-anchors", type: "buy", group: "Furniture Store", text: "Screws, anchors, and profile connectors", tasks: ["cloison"] },
    { id: "grenier-do-install-profiles", type: "do", text: "Repair minor plaster imperfections and sand smooth", tasks: ["painting"] },
    { id: "grenier-do-route-wiring", type: "do", text: "Route any additional electrical wiring for office sockets and lighting" },
    { id: "grenier-do-install-plasterboard", type: "do", text: "Protect floor and Velux frame before painting", tasks: ["painting"] },
    { id: "grenier-do-plaster-joints", type: "do", text: "Apply primer to all plastered wall and ceiling surfaces", tasks: ["painting"] },
    { id: "grenier-do-prime-pb", type: "do", text: "Apply first paint coat and inspect for touch-ups", tasks: ["painting"] },
    { id: "grenier-do-pvc-panels", type: "do", text: "Apply final paint coat and finish edges cleanly", tasks: ["painting"] },
    { id: "grenier-do-sockets", type: "do", text: "Install and connect power sockets" },
    { id: "grenier-do-light-fixtures", type: "do", text: "Install and test final light fixtures for office use" },
    { id: "grenier-do-parquet", type: "do", text: "Lay 8 mm underlayer and install parquet flooring", tasks: ["flooring"] },
    { id: "grenier-do-finishing", type: "do", text: "Final finishing, sealants, and cleanup" },
  ],
};
