export default {
  id: "kid-room",
  name: "Kid Room",
  icon: "🧸",
  items: [
    { id: "kid-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "kid-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "kid-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "kid-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "kid-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "kid-plan-wallpaper-wall", type: "plan", text: "Confirm which wall(s) will get wallpaper (feature wall or full room)" },
    { id: "kid-plan-wallpaper-measure", type: "plan", text: "Measure wall width and height and subtract large openings (door/window)" },
    { id: "kid-plan-wallpaper-waste", type: "plan", text: "Add 10-15% extra wallpaper for matching and cutting waste" },
    { id: "kid-plan-wallpaper-prep", type: "plan", text: "Check wall is smooth, dry, and dust-free before application" },
    { id: "kid-plan-wallpaper-align", type: "plan", text: "Decide final wallpaper alignment point for centered world map design" },
    { id: "kid-plan-curtains", type: "plan", text: "Curtains in Kid Room - confirm rail position, width, and final drop" },
    { id: "kid-plan-pax-dims", type: "plan", text: "IKEA PAX system in Kid Room - confirm dimensions, depth, and door swing clearance", tasks: ["ikea-pax"] },
    { id: "kid-plan-pax-wall", type: "plan", text: "IKEA PAX system in Kid Room - confirm wall type and fixing points for safe anchoring", tasks: ["ikea-pax"] },
    { id: "kid-plan-baby-timeline", type: "plan", text: "Baby due September – plan nursery setup timeline (move-in March, baby arrival September)" },
    { id: "kid-buy-crib", type: "buy", text: "Crib" },
    { id: "kid-buy-baby-mattress", type: "buy", text: "Crib mattress and waterproof protector" },
    { id: "kid-buy-baby-bedding", type: "buy", text: "Baby sheets, blankets, and sleep sacks" },
    { id: "kid-buy-changing-table", type: "buy", text: "IKEA combi/changing table" },
    { id: "kid-buy-change-mat", type: "buy", text: "Changing pad and covers" },
    { id: "kid-buy-baby-wipes-supplies", type: "buy", text: "Baby wipes, diapers storage, and changing supplies organizer" },
    { id: "kid-buy-feeding-chair", type: "buy", text: "Feeding/nursing chair" },
    { id: "kid-buy-baby-monitor", type: "buy", text: "Baby monitor (audio or video)" },
    { id: "kid-buy-blackout-curtains", type: "buy", text: "Blackout curtains or blinds for sleep hygiene" },
    { id: "kid-buy-curtains", type: "buy", text: "Additional curtains for Kid Room (layered with blackout)" },
    { id: "kid-buy-curtain-rail", type: "buy", text: "Curtain rail/rod and mounting brackets for Kid Room" },
    { id: "kid-buy-wallpaper", type: "buy", text: "Wallpaper (world map)" },
    { id: "kid-buy-wallpaper-glue", type: "buy", text: "Wallpaper glue" },
    { id: "kid-buy-wallpaper-roller", type: "buy", text: "Wallpaper roller or smoother" },
    { id: "kid-buy-seam-roller", type: "buy", text: "Seam roller" },
    { id: "kid-buy-knife", type: "buy", text: "Utility knife with spare blades" },
    { id: "kid-buy-ruler", type: "buy", text: "Metal ruler or long straight edge" },
    { id: "kid-buy-level", type: "buy", text: "Laser level or long spirit level" },
    { id: "kid-buy-primer-sealer", type: "buy", text: "Primer/sealer for wall prep if needed", tasks: ["painting"] },
    { id: "kid-buy-pax", type: "buy", text: "IKEA PAX frames and interior fittings for Kid Room", tasks: ["ikea-pax"] },
    { id: "kid-buy-baby-safety", type: "buy", text: "Baby safety items (outlet covers, corner guards, dresser anchors)" },
    { id: "kid-buy-storage-baskets", type: "buy", text: "Open storage baskets for toys and soft items" },
    { id: "kid-buy-name-plate", type: "buy", text: "Room name sign or wall decal (baby name or nursery theme)" },
    { id: "kid-do-prep-wall", type: "do", text: "Prepare wall: fill holes, sand lightly, and wipe clean" },
    { id: "kid-do-prime-wall", type: "do", text: "Apply primer/sealer and allow full drying", tasks: ["painting"] },
    { id: "kid-do-guideline", type: "do", text: "Mark first vertical guideline using plumb line or laser" },
    { id: "kid-do-apply-glue", type: "do", text: "Apply glue evenly with roller" },
    { id: "kid-do-first-strip", type: "do", text: "Install first wallpaper strip carefully and align pattern" },
    { id: "kid-do-match-strips", type: "do", text: "Add next strips and match map pattern edge-to-edge" },
    { id: "kid-do-smooth", type: "do", text: "Use smoother to remove air bubbles from center outward" },
    { id: "kid-do-trim", type: "do", text: "Trim top and bottom edges neatly with knife and straight edge" },
    { id: "kid-do-seams", type: "do", text: "Roll seams gently for proper adhesion" },
    { id: "kid-do-clean-glue", type: "do", text: "Clean excess glue immediately with damp sponge" },
    { id: "kid-do-cure", type: "do", text: "Let wallpaper cure fully before moving furniture against wall" },
    { id: "kid-do-curtain-rail", type: "do", text: "Install curtain rail/rod in Kid Room" },
    { id: "kid-do-hang-curtains", type: "do", text: "Hang curtains in Kid Room" },
    { id: "kid-do-order-pax", type: "do", text: "Order IKEA PAX system for Kid Room", tasks: ["ikea-pax"] },
    { id: "kid-do-assemble-pax", type: "do", text: "Assemble and fix IKEA PAX system in Kid Room", tasks: ["ikea-pax"] },
    { id: "kid-do-baby-safety-install", type: "do", text: "Install all baby safety items (outlet covers, corner guards, dresser anchors)" },
    { id: "kid-do-setup-changing", type: "do", text: "Set up changing table with mat, covers, and supply organizer" },
    { id: "kid-do-setup-sleep", type: "do", text: "Assemble crib, install mattress and protector, arrange bedding" },
    { id: "kid-do-setup-monitor", type: "do", text: "Install and test baby monitor (position for clear room view)" },
    { id: "kid-do-arrange-storage", type: "do", text: "Arrange storage baskets and clothing for easy parent access" },
  ],
};