export default {
  id: "kitchen",
  name: "Kitchen",
  icon: "🍳",
  items: [
    { id: "kitchen-plan-check-walls", type: "plan", text: "Walls and ceiling are plastered, smooth, and ready for primer and paint", tasks: ["provisional-acceptance"] },
    { id: "kitchen-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "kitchen-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "kitchen-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "kitchen-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "kitchen-plan-layout", type: "plan", text: "Confirm final kitchen layout against electrical and plumbing points" },
    { id: "kitchen-plan-appliances", type: "plan", text: "Confirm extractor, appliance, and worktop dimensions before ordering" },
    { id: "kitchen-plan-plank-anchors", type: "plan", text: "Confirm ceiling anchor points for suspended overhead plank above kitchen island (open living-kitchen space)", tasks: ["furniture-making"] },
    { id: "kitchen-buy-stools", type: "buy", group: "Furniture Store", text: "3 high stools for kitchen" },
    { id: "kitchen-buy-milk-utensil", type: "buy", group: "IKEA", text: "Milk utensil from IKEA" },
    { id: "kitchen-buy-dustbin", type: "buy", group: "Appliances", text: "Dustbin pull-out mechanism" },
    { id: "kitchen-buy-plank-anchors", type: "buy", group: "Furniture Store", text: "Ceiling anchors and hardware for suspended overhead plank above kitchen island", tasks: ["furniture-making"] },
    { id: "kitchen-buy-pantry", type: "buy", group: "Furniture Store", text: "Shelving or pantry organizers for everyday storage" },
    { id: "kitchen-buy-cable-covers", type: "buy", group: "Electricals", text: "Cable covers or clips for small-appliance zones" },
    { id: "kitchen-do-verify-appliances", type: "do", text: "Verify final appliance list against the available sockets and plumbing points" },
    { id: "kitchen-do-cut-list", type: "do", text: "Prepare cut list for each furniture item", tasks: ["furniture-making"] },
    { id: "kitchen-do-cut-label", type: "do", text: "Cut and label all parts", tasks: ["furniture-making"] },
    { id: "kitchen-do-cut-pine", type: "do", text: "Cut pine and plywood pieces to final dimensions", tasks: ["furniture-making"] },
    { id: "kitchen-do-dry-fit", type: "do", text: "Dry-fit components before final assembly", tasks: ["furniture-making"] },
    { id: "kitchen-do-assemble-sandwich", type: "do", text: "Assemble sandwich panel with glue and internal plywood supports", tasks: ["furniture-making"] },
    { id: "kitchen-do-assemble-square", type: "do", text: "Assemble and square each unit", tasks: ["furniture-making"] },
    { id: "kitchen-do-dust-glue-fill", type: "do", text: "Fill gaps and screw holes with dust-glue mix (oak dust for oak areas, spruce dust for spruce areas)", tasks: ["furniture-making"] },
    { id: "kitchen-do-sand-all", type: "do", text: "Sand all assembled parts (start medium grit, finish with 240 grit by hand before final coats)", tasks: ["furniture-making"] },
    { id: "kitchen-do-pu-coating", type: "do", text: "Apply Fond Dur PU coating on plywood and high-exposure edges (minimum three coats)", tasks: ["furniture-making"] },
    { id: "kitchen-do-sand-between-coats", type: "do", text: "Lightly sand by hand with 240 grit between PU coats when fibers rise", tasks: ["furniture-making"] },
    { id: "kitchen-do-route-plank", type: "do", text: "Route the 5cm side cuts for the 200x30cm overhead plank", tasks: ["furniture-making"] },
    { id: "kitchen-do-glue-plank", type: "do", text: "Glue the four side cuts to the 200x30cm overhead plank and clamp for curing", tasks: ["furniture-making"] },
    { id: "kitchen-do-install-plank", type: "do", text: "Install suspended overhead plank above kitchen island (open living-kitchen space) using ceiling anchors", tasks: ["furniture-making"] },
    { id: "kitchen-do-blind-position", type: "do", text: "Mark any shelf, rail, or blind fixing positions before drilling" },
    { id: "kitchen-do-blind", type: "do", text: "Install the selected curtain or blind solution if required" },
    { id: "kitchen-do-task-lighting", type: "do", text: "Install and test under-cabinet or task lighting" },
    { id: "kitchen-do-cable-tidy", type: "do", text: "Organize countertop appliance zones and tidy visible cable routing" },
  ],
};
