export default {
  id: "living-room",
  name: "Living Room",
  icon: "🛋️",
  items: [
    { id: "living-plan-check-walls", type: "plan", text: "Walls and ceiling are plastered, smooth, and ready for primer and paint", tasks: ["provisional-acceptance"] },
    { id: "living-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "living-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "living-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "living-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "living-plan-curtain-rails", type: "plan", text: "Confirm curtain rail positions and lengths for all glazing" },
    { id: "living-plan-plank-anchors", type: "plan", text: "Confirm ceiling anchor points for suspended overhead plank above kitchen island (open living-kitchen space)", tasks: ["furniture-making"] },
    { id: "living-buy-curtains", type: "buy", group: "Textiles & Decor", text: "Curtains from India - Check for better prices and variety" },
    { id: "living-buy-curtain-rails", type: "buy", group: "Textiles & Decor", text: "Curtain rails and mounting hardware - double rails for layered curtains" },
    { id: "living-buy-curtain-hooks", type: "buy", group: "Textiles & Decor", text: "Curtain hooks or rings if needed for the chosen curtains" },
    { id: "living-buy-plank-anchors", type: "buy", group: "Furniture Store", text: "Ceiling anchors and hardware for suspended overhead plank above kitchen island", tasks: ["furniture-making"] },
    { id: "living-buy-spruce-planks", type: "buy", group: "Furniture Store", text: "Spruce planks for wall shelves", tasks: ["furniture-making"] },
    { id: "living-buy-fond-dur", type: "buy", group: "Paint", text: "Ancien Ebeniste Fond Dur", tasks: ["furniture-making"] },
    { id: "living-buy-v33", type: "buy", group: "Paint", text: "V33 Smoke Mat finish", tasks: ["furniture-making"] },
    { id: "living-do-curtain-rails", type: "do", text: "Install curtain rails and confirm both lines run level across the glazing" },
    { id: "living-do-hang-curtains", type: "do", text: "Hang curtains and check full open-close movement without dragging" },
    { id: "living-do-cut-list", type: "do", text: "Prepare cut list for each furniture item", tasks: ["furniture-making"] },
    { id: "living-do-cut-label", type: "do", text: "Cut and label all parts", tasks: ["furniture-making"] },
    { id: "living-do-route-plank", type: "do", text: "Route the 5cm side cuts for the 200x30cm overhead plank", tasks: ["furniture-making"] },
    { id: "living-do-glue-plank", type: "do", text: "Glue the four side cuts to the 200x30cm overhead plank and clamp for curing", tasks: ["furniture-making"] },
    { id: "living-do-install-plank", type: "do", text: "Install suspended overhead plank above kitchen island (open living-kitchen space) using ceiling anchors", tasks: ["furniture-making"] },
    { id: "living-do-cut-spruce", type: "do", text: "Cut spruce pieces for wall shelves", tasks: ["furniture-making"] },
    { id: "living-do-glue-spruce", type: "do", text: "Glue the spruce planks for wall shelves", tasks: ["furniture-making"] },
    { id: "living-do-dust-glue-fill", type: "do", text: "Fill gaps and screw holes with dust-glue mix (oak dust for oak areas, spruce dust for spruce areas)", tasks: ["furniture-making"] },
    { id: "living-do-sand-all", type: "do", text: "Sand all assembled parts (start medium grit, finish with 240 grit by hand before final coats)", tasks: ["furniture-making"] },
    { id: "living-do-sand-all", type: "do", text: "Sand all assembled parts (start medium grit, finish with 240 grit by hand before final coats)", tasks: ["furniture-making"] },
    { id: "living-do-condition-spruce", type: "do", text: "Condition spruce with Ancien Ebeniste Fond Dur", tasks: ["furniture-making"] },
    { id: "living-do-v33-finish", type: "do", text: "Apply V33 Smoke Mat finish to oak plank and spruce shelves", tasks: ["furniture-making"] },
    { id: "living-do-mount-shelves", type: "do", text: "Mount prepared wall floating shelves", tasks: ["furniture-making"] },
    { id: "living-do-cleanup", type: "do", text: "Complete final touch-ups and cleanup after drilling and shelf installation" },
  ],
};
