export default {
  id: "outside-house",
  name: "Outside House",
  icon: "🏡",
  items: [
    { id: "outside-plan-postbox", type: "plan", text: "Check local rules or common practice for post box position and height" },
    { id: "outside-plan-number-plate", type: "plan", text: "Confirm number plate placement is clearly visible from the street" },
    { id: "outside-plan-camera", type: "plan", text: "Check Wi-Fi or power availability for the safety camera" },
    { id: "outside-plan-lights-rating", type: "plan", text: "Choose outdoor lights and camera with suitable weather rating" },
    { id: "outside-plan-cable-routing", type: "plan", text: "Plan cable routing or mounting points before drilling outside walls" },
    { id: "outside-buy-postbox", type: "buy", group: "Garden & Outdoor", text: "Post box" },
    { id: "outside-buy-number-plate", type: "buy", group: "Garden & Outdoor", text: "Number plate" },
    { id: "outside-buy-garden", type: "buy", group: "Garden & Outdoor", text: "Rose plants and basic garden tools" },
    { id: "outside-buy-lights", type: "buy", group: "Garden & Outdoor", text: "Outdoor lights" },
    { id: "outside-buy-camera", type: "buy", group: "Garden & Outdoor", text: "Safety camera" },
    { id: "outside-buy-fixings", type: "buy", group: "Garden & Outdoor", text: "Weatherproof fixings and cable protection" },
    { id: "outside-buy-film", type: "buy", group: "Garden & Outdoor", text: "Film for glass door - security and privacy" },
    { id: "outside-do-locate-postbox", type: "do", text: "Identify location for post box" },
    { id: "outside-do-locate-plate", type: "do", text: "Identify location for number plate" },
    { id: "outside-do-locate-lights", type: "do", text: "Identify locations for outdoor lights and safety camera" },
    { id: "outside-do-install-postbox", type: "do", text: "Install the post box" },
    { id: "outside-do-install-plate", type: "do", text: "Install the number plate" },
    { id: "outside-do-install-lights", type: "do", text: "Install outdoor lights" },
    { id: "outside-do-install-camera", type: "do", text: "Install and test safety camera" },
    { id: "outside-do-install-film", type: "do", text: "Apply privacy and security film to glass door" },
    { id: "outside-do-plant-rose", type: "do", text: "Plant the rose plant" },
  ],
};
