export default {
  id: "painting",
  name: "Painting",
  icon: "🎨",
  items: [
    { id: "painting-plan-rooms", type: "plan", text: "Confirm which rooms will stay Polarweiss white and which need room-specific wall colors (Buanderie color TBD)", tasks: ["painting"] },
    { id: "painting-plan-ceiling-color", type: "plan", text: "Decide ceiling color per room: Polarweiss throughout or match room walls", tasks: ["painting"] },
    { id: "painting-plan-quantities", type: "plan", text: "Estimate primer and paint quantities for dressing room, buanderie, and priority rooms", tasks: ["painting"] },
    { id: "painting-plan-test-shades", type: "plan", text: "Test selected paint shades in daylight and evening light before placing final orders", tasks: ["painting"] },
    { id: "painting-plan-wallpaper-scope", type: "plan", text: "Confirm whether the kid room wallpaper stays in scope for the first move-in phase", tasks: ["painting"] },
    { id: "painting-buy-tiefgrund", type: "buy", text: "Tiefgrund LF primer for walls and ceilings (source: Aachen)", tasks: ["painting"] },
    { id: "painting-buy-plasterboard-primer", type: "buy", text: "Plasterboard primer (confirm compatibility with Tiefgrund or use alternative)", tasks: ["painting", "cloison"] },
    { id: "painting-buy-ceiling-paint", type: "buy", text: "Ceiling paint (Polarweiss or chosen shade)", tasks: ["painting"] },
    { id: "painting-buy-wall-paint", type: "buy", text: "Wall paint (room-specific colors)", tasks: ["painting"] },
    { id: "painting-buy-rollers", type: "buy", text: "Rollers", tasks: ["painting"] },
    { id: "painting-buy-brushes", type: "buy", text: "Brushes", tasks: ["painting"] },
    { id: "painting-buy-trays", type: "buy", text: "Paint trays", tasks: ["painting"] },
    { id: "painting-buy-drop-cloths", type: "buy", text: "Drop cloths", tasks: ["painting"] },
    { id: "painting-buy-tape", type: "buy", text: "Painter tape", tasks: ["painting"] },
    { id: "painting-buy-sandpaper", type: "buy", text: "Sandpaper", tasks: ["painting"] },
    { id: "painting-buy-mdf-primer", type: "buy", text: "MDF primer", tasks: ["painting"] },
    { id: "painting-buy-mdf-topcoat", type: "buy", text: "MDF topcoat", tasks: ["painting"] },
    { id: "painting-buy-plastic", type: "buy", text: "Plastic sheeting", tasks: ["painting"] },
    { id: "painting-buy-extension-pole", type: "buy", text: "Extension pole for roller", tasks: ["painting"] },
    { id: "painting-buy-ladder", type: "buy", text: "Ladder or step stool for reaching high areas", tasks: ["painting"] },
    { id: "painting-do-prime-all", type: "do", text: "Prime all walls and ceilings with Tiefgrund LF", tasks: ["painting"] },
    { id: "painting-do-ceilings", type: "do", text: "Paint ceilings – Polarweiss white or matching wall shade", tasks: ["painting"] },
    { id: "painting-do-touch-ups", type: "do", text: "Paint touch-ups after installing fixtures and furniture", tasks: ["painting"] },
  ],
};
