export default {
  id: "second-bedroom",
  name: "Second Bedroom",
  icon: "🛌",
  items: [
    { id: "second-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "second-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "second-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "second-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "second-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "second-plan-curtains", type: "plan", text: "Curtains in Second Bedroom - confirm rail position, width, and final drop" },
    { id: "second-plan-pax-dims", type: "plan", text: "IKEA PAX system in Second Bedroom - confirm dimensions, depth, and door swing clearance", tasks: ["ikea-pax"] },
    { id: "second-plan-pax-wall", type: "plan", text: "IKEA PAX system in Second Bedroom - confirm wall type and fixing points for safe anchoring", tasks: ["ikea-pax"] },
    { id: "second-buy-bed", type: "buy", text: "Bed for Second Bedroom" },
    { id: "second-buy-mattress", type: "buy", text: "Mattress for Second Bedroom" },
    { id: "second-buy-bedsheet", type: "buy", text: "Bedsheet set for Second Bedroom" },
    { id: "second-buy-pillows", type: "buy", text: "Pillows for Second Bedroom" },
    { id: "second-buy-pillow-covers", type: "buy", text: "Pillow covers for Second Bedroom" },
    { id: "second-buy-duvet", type: "buy", text: "Blanket or duvet for Second Bedroom" },
    { id: "second-buy-duvet-cover", type: "buy", text: "Duvet cover for Second Bedroom" },
    { id: "second-buy-mattress-protector", type: "buy", text: "Mattress protector for Second Bedroom" },
    { id: "second-buy-curtains", type: "buy", text: "Curtains for Second Bedroom" },
    { id: "second-buy-curtain-rail", type: "buy", text: "Curtain rail/rod and mounting brackets for Second Bedroom" },
    { id: "second-buy-pax", type: "buy", text: "IKEA PAX frames and interior fittings for Second Bedroom", tasks: ["ikea-pax"] },
    { id: "second-buy-wall-anchors", type: "buy", text: "Wall anchors and screws by wall type", tasks: ["ikea-pax"] },
    { id: "second-do-curtain-rail", type: "do", text: "Install curtain rail/rod in Second Bedroom" },
    { id: "second-do-hang-curtains", type: "do", text: "Hang curtains in Second Bedroom" },
    { id: "second-do-order-pax", type: "do", text: "Order IKEA PAX system for Second Bedroom", tasks: ["ikea-pax"] },
    { id: "second-do-assemble-pax", type: "do", text: "Assemble and fix IKEA PAX system in Second Bedroom", tasks: ["ikea-pax"] },
  ],
};
