export default {
  id: "stairs",
  name: "Stairs",
  icon: "🪜",
  items: [
    { id: "stairs-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "stairs-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "stairs-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "stairs-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "stairs-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "stairs-plan-rail-height", type: "plan", text: "Confirm rail height and angle along full staircase run" },
    { id: "stairs-plan-wall-material", type: "plan", text: "Verify wall material and locate solid fixing points" },
    { id: "stairs-plan-profiles", type: "plan", text: "Confirm 1 m profiles fit all sections and joints are planned" },
    { id: "stairs-plan-beams-position", type: "plan", text: "Plan position of 44x44 mm support beams behind rail profiles" },
    { id: "stairs-plan-led-power", type: "plan", text: "Identify nearest power outlet for stair LED supply" },
    { id: "stairs-plan-led-driver", type: "plan", text: "Plan LED driver location with future access for maintenance" },
    { id: "stairs-plan-switch", type: "plan", text: "Decide switch control method (existing wall switch, added switch, or sensor)" },
    { id: "stairs-buy-beams", type: "buy", text: "44x44 mm wooden support beams" },
    { id: "stairs-buy-anchors", type: "buy", text: "Wall anchors and screws by wall type" },
    { id: "stairs-buy-led-strips", type: "buy", text: "LED strips" },
    { id: "stairs-buy-led-profiles", type: "buy", text: "LED aluminum profiles" },
    { id: "stairs-buy-led-drivers", type: "buy", text: "LED drivers" },
    { id: "stairs-buy-cable", type: "buy", text: "Low-voltage cable" },
    { id: "stairs-buy-switch", type: "buy", text: "Switch or sensor module for stair lighting control" },
    { id: "stairs-buy-cable-clips", type: "buy", text: "Cable clips or trunking" },
    { id: "stairs-buy-under-stairs-shelves", type: "buy", text: "Shelves or shelf boards for under-stairs storage", tasks: ["furniture-making"] },
    { id: "stairs-do-mark-rail", type: "do", text: "Mark rail line and bracket positions with a level" },
    { id: "stairs-do-beams", type: "do", text: "Cut and pre-drill 44x44 mm support beams as needed" },
    { id: "stairs-do-fix-beams", type: "do", text: "Fix support beams securely to wall structure" },
    { id: "stairs-do-mount-profiles", type: "do", text: "Mount 1 m rail profiles onto supports and check alignment" },
    { id: "stairs-do-led-profile", type: "do", text: "Install LED profile underneath rail" },
    { id: "stairs-do-run-cable", type: "do", text: "Run low-voltage cable from LED profile to driver location" },
    { id: "stairs-do-led-strip", type: "do", text: "Install LED strip in profile and connect to driver" },
    { id: "stairs-do-connect-driver", type: "do", text: "Connect driver to power outlet/circuit safely" },
    { id: "stairs-do-switch", type: "do", text: "Install and test selected switch/sensor control" },
    { id: "stairs-do-test-lighting", type: "do", text: "Test full staircase lighting at day and night brightness" },
    { id: "stairs-do-cable-tidy", type: "do", text: "Secure all cables and close any visible routing neatly" },
    { id: "stairs-do-install-under-stairs-shelves", type: "do", text: "Install shelves under the stairs for cleaning products and detergent", tasks: ["furniture-making"] },
  ],
};