export default {
  id: "timeline",
  name: "Timeline",
  icon: "🗓️",
  items: [
    { id: "tl-plan-step1-visit", type: "plan", group: "Step 1 - Pre-Key Visit and Paint Readiness", text: "Visit house and do a room-by-room check with photos" },
    { id: "tl-plan-step1-paint-decisions", type: "plan", group: "Step 1 - Pre-Key Visit and Paint Readiness", text: "Finalize paint decisions: primer type, ceiling color, wall color per room" },
    { id: "tl-plan-step1-paint-kit", type: "plan", group: "Step 1 - Pre-Key Visit and Paint Readiness", text: "Prepare painting setup kit: painter tape, plastic sheet, floor ground cover/drop cloths, masking film, trays, rollers, brushes" },
    { id: "tl-plan-step1-quantities", type: "plan", group: "Step 1 - Pre-Key Visit and Paint Readiness", text: "Estimate quantity of primer and paint for dressing + priority rooms" },
    { id: "tl-plan-step1-india-list", type: "plan", group: "Step 1 - Pre-Key Visit and Paint Readiness", text: "Prepare final India buy list (curtains, hand faucets, pressure cooker, selected hardware)" },
    { id: "tl-plan-step2-deed", type: "plan", group: "Step 2 - Deed and Key Handover", text: "Sign deed / house papers (April 1)" },
    { id: "tl-plan-step2-keys", type: "plan", group: "Step 2 - Deed and Key Handover", text: "Get keys and confirm utility handover references" },
    { id: "tl-plan-step2-defects", type: "plan", group: "Step 2 - Deed and Key Handover", text: "Record immediate defects or pending items" },
    { id: "tl-plan-step3-india-travel", type: "plan", group: "Step 3 - India Trip Window", text: "Travel to India (April 25 to May 18)" },
    { id: "tl-plan-step3-curtains", type: "plan", group: "Step 3 - India Trip Window", text: "Buy curtains and selected fittings if quality/price is better" },
    { id: "tl-plan-step3-bidet", type: "plan", group: "Step 3 - India Trip Window", text: "Buy hand faucet / bidet spray sets if quality/price is better" },
    { id: "tl-plan-step3-cooker", type: "plan", group: "Step 3 - India Trip Window", text: "Buy steel pressure cooker (1.5L)" },
    { id: "tl-plan-step3-confirm", type: "plan", group: "Step 3 - India Trip Window", text: "Return with final quantities and measurements confirmed" },
    { id: "tl-plan-step4-pax", type: "plan", group: "Step 4 - Immediate Post-India Orders (Week 1)", text: "Order dressing room IKEA PAX system first" },
    { id: "tl-plan-step4-materials", type: "plan", group: "Step 4 - Immediate Post-India Orders (Week 1)", text: "Order plasterboards and MDF (18 mm and 6 mm) for dressing and related works" },
    { id: "tl-plan-step4-hardware", type: "plan", group: "Step 4 - Immediate Post-India Orders (Week 1)", text: "Order anchors, screws, fillers, caulk, and electrical accessories" },
    { id: "tl-plan-step5-dressing-paint", type: "plan", group: "Step 5 - Painting and Dressing Unblock (Week 1-2)", text: "Prime and paint dressing room first" },
    { id: "tl-plan-step5-priority-paint", type: "plan", group: "Step 5 - Painting and Dressing Unblock (Week 1-2)", text: "In parallel: prime other priority areas" },
    { id: "tl-plan-step5-paint-workflow", type: "plan", group: "Step 5 - Painting and Dressing Unblock (Week 1-2)", text: "Complete painting prep workflow before each room: tape edges, lay plastic sheet and ground cover, protect switches/sockets, then prime/paint" },
    { id: "tl-plan-step5-pax-assembly", type: "plan", group: "Step 5 - Painting and Dressing Unblock (Week 1-2)", text: "Start dressing PAX assembly as soon as the room is paint-ready and materials are delivered" },
    { id: "tl-plan-step6-movein", type: "plan", group: "Step 6 - Move-In Start and Core Installations", text: "Start shifting / move-in once dressing and basic painted areas are usable" },
    { id: "tl-plan-step6-stairs", type: "plan", group: "Step 6 - Move-In Start and Core Installations", text: "Install stair rails and stair LED setup" },
    { id: "tl-plan-step6-grenier-plasterboard", type: "plan", group: "Step 6 - Move-In Start and Core Installations", text: "Start grenier plasterboard framework and boarding" },
    { id: "tl-plan-step7-pax-order", type: "plan", group: "Step 7 - Expand Storage Across House", text: "Order IKEA PAX units for ground corridor, upstairs corridor, second bedroom, and kid room" },
    { id: "tl-plan-step7-corridor-unit", type: "plan", group: "Step 7 - Expand Storage Across House", text: "Order and install Ground Corridor entrance unit details (PAX + METOD + wall panel)" },
    { id: "tl-plan-step7-install-pax", type: "plan", group: "Step 7 - Expand Storage Across House", text: "Install PAX units to each room" },
    { id: "tl-plan-step7-bedroom2-bed", type: "plan", group: "Step 7 - Expand Storage Across House", text: "Furnish Second Bedroom with bed, mattress, and full bed setup" },
    { id: "tl-plan-step7-bedroom2-complete", type: "plan", group: "Step 7 - Expand Storage Across House", text: "Complete Second Bedroom setup after PAX installation and curtains" },
    { id: "tl-plan-step8-greenhouse-order", type: "plan", group: "Step 8 - Greenhouse", text: "Order greenhouse (after model research and Gaetan power check)" },
    { id: "tl-plan-step8-greenhouse-install", type: "plan", group: "Step 8 - Greenhouse", text: "Prepare base and install greenhouse" },
    { id: "tl-plan-step9-flooring-order", type: "plan", group: "Step 9 - Grenier Finishing", text: "Order grenier flooring (parquet + 8 mm underlayer)" },
    { id: "tl-plan-step9-panels-order", type: "plan", group: "Step 9 - Grenier Finishing", text: "Order grenier PVC wall panels and panel glue" },
    { id: "tl-plan-step9-flooring-install", type: "plan", group: "Step 9 - Grenier Finishing", text: "Install grenier flooring and wall panels after plasterboard/primer readiness" },
    { id: "tl-plan-step10-touchups", type: "plan", group: "Step 10 - Closeout and Buffer", text: "Final touch-ups and room checks" },
    { id: "tl-plan-step10-buffer", type: "plan", group: "Step 10 - Closeout and Buffer", text: "Keep a buffer for delivery delays and rework" },
    { id: "tl-plan-step10-leave", type: "plan", group: "Step 10 - Closeout and Buffer", text: "Track apartment leave target (June 30)" },
  ]
};
