export default {
  id: "toilets",
  name: "Toilets",
  icon: "🚽",
  items: [
    { id: "toilets-plan-check-walls", type: "plan", text: "Walls and ceiling are plastered, smooth, and ready for primer and paint", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "toilets-gf-plan-supply-type", type: "plan", group: "Toilet (Ground Floor)", text: "Confirm water supply connection type and pipe diameter" },
    { id: "toilets-gf-plan-shutoff", type: "plan", group: "Toilet (Ground Floor)", text: "Check existing shut-off valve condition and accessibility" },
    { id: "toilets-gf-plan-bracket-space", type: "plan", group: "Toilet (Ground Floor)", text: "Measure space beside toilet for hand faucet (bidet spray) bracket" },
    { id: "toilets-gf-plan-wall-type", type: "plan", group: "Toilet (Ground Floor)", text: "Confirm wall material for bracket mounting (tile vs plasterboard vs masonry)" },
    { id: "toilets-gf-plan-pressure", type: "plan", group: "Toilet (Ground Floor)", text: "Check water pressure is sufficient for hand faucet operation" },

    { id: "toilets-ff-plan-supply-type", type: "plan", group: "Toilet (First Floor)", text: "Confirm water supply connection type and pipe diameter" },
    { id: "toilets-ff-plan-shutoff", type: "plan", group: "Toilet (First Floor)", text: "Check existing shut-off valve condition and accessibility" },
    { id: "toilets-ff-plan-bracket-space", type: "plan", group: "Toilet (First Floor)", text: "Measure space beside toilet for hand faucet (bidet spray) bracket" },
    { id: "toilets-ff-plan-wall-type", type: "plan", group: "Toilet (First Floor)", text: "Confirm wall material for bracket mounting (tile vs plasterboard vs masonry)" },
    { id: "toilets-ff-plan-pressure", type: "plan", group: "Toilet (First Floor)", text: "Check water pressure is sufficient for hand faucet operation" },
    { id: "toilets-ff-plan-ikea-washbasin", type: "plan", group: "Toilet (First Floor)", text: "Confirm dimensions and plumbing points for IKEA washbasin", tasks: ["ikea-pax"] },

    { id: "toilets-gf-buy-bidet-kits", type: "buy", group: "Plumbing", text: "GF toilet: hand faucet / bidet spray kit" },
    { id: "toilets-gf-buy-paper-mounts", type: "buy", group: "Plumbing", text: "GF toilet: toilet paper mount" },
    { id: "toilets-gf-buy-t-valves", type: "buy", group: "Plumbing", text: "GF toilet: T-valve and T-adapter" },
    { id: "toilets-gf-buy-hoses", type: "buy", group: "Plumbing", text: "GF toilet: braided hose" },
    { id: "toilets-gf-buy-bracket", type: "buy", group: "Plumbing", text: "GF toilet: wall bracket / holder for hand faucet" },

    { id: "toilets-ff-buy-bidet-kits", type: "buy", group: "Plumbing", text: "FF toilet: hand faucet / bidet spray kit" },
    { id: "toilets-ff-buy-paper-mounts", type: "buy", group: "Plumbing", text: "FF toilet: toilet paper mount" },
    { id: "toilets-ff-buy-t-valves", type: "buy", group: "Plumbing", text: "FF toilet: T-valve and T-adapter" },
    { id: "toilets-ff-buy-hoses", type: "buy", group: "Plumbing", text: "FF toilet: braided hose" },
    { id: "toilets-ff-buy-bracket", type: "buy", group: "Plumbing", text: "FF toilet: wall bracket / holder for hand faucet" },
    { id: "toilets-ff-buy-ikea-washbasin", type: "buy", group: "IKEA", text: "FF toilet: IKEA washbasin and fittings", tasks: ["ikea-pax"] },

    { id: "toilets-buy-ptfe", type: "buy", group: "Plumbing", text: "PTFE thread tape" },
    { id: "toilets-buy-anchors", type: "buy", group: "Plumbing", text: "Wall anchors and screws by wall type" },
    { id: "toilets-buy-wrench", type: "buy", group: "Tools & Safety", text: "Adjustable wrench" },
    { id: "toilets-buy-basin-wrench", type: "buy", group: "Tools & Safety", text: "Basin wrench" },
    { id: "toilets-buy-buckets", type: "buy", group: "General", text: "Buckets and towels" },
    { id: "toilets-buy-shutoff-valves", type: "buy", group: "Plumbing", text: "Shut-off valves if replacements are needed" },

    { id: "toilets-gf-do-shutoff-water", type: "do", group: "Toilet (Ground Floor)", text: "Turn off water supply at shut-off valve" },
    { id: "toilets-gf-do-flush", type: "do", group: "Toilet (Ground Floor)", text: "Flush toilet to clear remaining water from cistern" },
    { id: "toilets-gf-do-disconnect-hose", type: "do", group: "Toilet (Ground Floor)", text: "Disconnect existing supply hose from cistern inlet" },
    { id: "toilets-gf-do-t-adapter", type: "do", group: "Toilet (Ground Floor)", text: "Fit T-adapter onto shut-off valve using PTFE tape" },
    { id: "toilets-gf-do-reconnect-cistern", type: "do", group: "Toilet (Ground Floor)", text: "Reconnect existing cistern hose to one T-adapter port" },
    { id: "toilets-gf-do-connect-hose", type: "do", group: "Toilet (Ground Floor)", text: "Connect new flexible hose from second T-adapter port" },
    { id: "toilets-gf-do-drill-bracket", type: "do", group: "Toilet (Ground Floor)", text: "Mark and drill bracket position at reachable height" },
    { id: "toilets-gf-do-fix-bracket", type: "do", group: "Toilet (Ground Floor)", text: "Fix wall bracket securely with appropriate plugs/screws" },
    { id: "toilets-gf-do-attach-holder", type: "do", group: "Toilet (Ground Floor)", text: "Attach hand faucet holder to bracket" },
    { id: "toilets-gf-do-paper-mounts", type: "do", group: "Toilet (Ground Floor)", text: "Install toilet paper mount at comfortable reach height" },
    { id: "toilets-gf-do-connect-faucet", type: "do", group: "Toilet (Ground Floor)", text: "Connect flexible hose to hand faucet" },
    { id: "toilets-gf-do-turn-on", type: "do", group: "Toilet (Ground Floor)", text: "Turn water supply back on and check joints for leaks" },
    { id: "toilets-gf-do-test-faucet", type: "do", group: "Toilet (Ground Floor)", text: "Test hand faucet and adjust flow" },

    { id: "toilets-ff-do-shutoff-water", type: "do", group: "Toilet (First Floor)", text: "Turn off water supply at shut-off valve" },
    { id: "toilets-ff-do-flush", type: "do", group: "Toilet (First Floor)", text: "Flush toilet to clear remaining water from cistern" },
    { id: "toilets-ff-do-disconnect-hose", type: "do", group: "Toilet (First Floor)", text: "Disconnect existing supply hose from cistern inlet" },
    { id: "toilets-ff-do-t-adapter", type: "do", group: "Toilet (First Floor)", text: "Fit T-adapter onto shut-off valve using PTFE tape" },
    { id: "toilets-ff-do-reconnect-cistern", type: "do", group: "Toilet (First Floor)", text: "Reconnect existing cistern hose to one T-adapter port" },
    { id: "toilets-ff-do-connect-hose", type: "do", group: "Toilet (First Floor)", text: "Connect new flexible hose from second T-adapter port" },
    { id: "toilets-ff-do-drill-bracket", type: "do", group: "Toilet (First Floor)", text: "Mark and drill bracket position at reachable height" },
    { id: "toilets-ff-do-fix-bracket", type: "do", group: "Toilet (First Floor)", text: "Fix wall bracket securely with appropriate plugs/screws" },
    { id: "toilets-ff-do-attach-holder", type: "do", group: "Toilet (First Floor)", text: "Attach hand faucet holder to bracket" },
    { id: "toilets-ff-do-paper-mounts", type: "do", group: "Toilet (First Floor)", text: "Install toilet paper mount at comfortable reach height" },
    { id: "toilets-ff-do-connect-faucet", type: "do", group: "Toilet (First Floor)", text: "Connect flexible hose to hand faucet" },
    { id: "toilets-ff-do-turn-on", type: "do", group: "Toilet (First Floor)", text: "Turn water supply back on and check joints for leaks" },
    { id: "toilets-ff-do-test-faucet", type: "do", group: "Toilet (First Floor)", text: "Test hand faucet and adjust flow" },
    { id: "toilets-ff-do-install-ikea-washbasin", type: "do", group: "Toilet (First Floor)", text: "Install and align IKEA washbasin, connect trap and water lines", tasks: ["ikea-pax"] },
  ],
};
