export default {
  id: "toilets",
  name: "Toilets",
  icon: "🚽",
  items: [
    { id: "toilets-plan-check-walls", type: "plan", text: "Walls and ceiling are finished (primer, paint, and touch-ups complete)", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-floor", type: "plan", text: "Floor finish is complete and protected during remaining works", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-sockets", type: "plan", text: "Sockets, switches, and lights are tested and working", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-doors", type: "plan", text: "Doors and windows open, close, and seal correctly", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-check-skirting", type: "plan", text: "Skirting, caulk, and paint edges are clean and complete", tasks: ["provisional-acceptance"] },
    { id: "toilets-plan-supply-type", type: "plan", text: "Confirm water supply connection type and pipe diameter at each toilet" },
    { id: "toilets-plan-shutoff", type: "plan", text: "Check existing shut-off valve condition and accessibility" },
    { id: "toilets-plan-bracket-space", type: "plan", text: "Measure the space available beside the toilet for the hand faucet (bidet spray) bracket" },
    { id: "toilets-plan-wall-type", type: "plan", text: "Confirm wall material for bracket mounting (tile vs plasterboard vs masonry)" },
    { id: "toilets-plan-pressure", type: "plan", text: "Check water pressure is sufficient for hand faucet operation" },
    { id: "toilets-buy-bidet-kits", type: "buy", text: "Hand faucet / bidet spray kits" },
    { id: "toilets-buy-paper-mounts", type: "buy", text: "Toilet paper mounts" },
    { id: "toilets-buy-t-valves", type: "buy", text: "T-valves and T-adapters" },
    { id: "toilets-buy-hoses", type: "buy", text: "Braided hoses" },
    { id: "toilets-buy-bracket", type: "buy", text: "Wall-mounted bracket / holder for the hand faucet" },
    { id: "toilets-buy-ptfe", type: "buy", text: "PTFE thread tape" },
    { id: "toilets-buy-anchors", type: "buy", text: "Wall anchors and screws by wall type" },
    { id: "toilets-buy-wrench", type: "buy", text: "Adjustable wrench" },
    { id: "toilets-buy-basin-wrench", type: "buy", text: "Basin wrench" },
    { id: "toilets-buy-buckets", type: "buy", text: "Buckets and towels" },
    { id: "toilets-buy-shutoff-valves", type: "buy", text: "Shut-off valves if replacements are needed" },
    { id: "toilets-do-shutoff-water", type: "do", text: "Turn off water supply at the shut-off valve under the toilet" },
    { id: "toilets-do-flush", type: "do", text: "Flush toilet to clear remaining water from the cistern" },
    { id: "toilets-do-disconnect-hose", type: "do", text: "Disconnect existing supply hose from the cistern inlet" },
    { id: "toilets-do-t-adapter", type: "do", text: "Fit the T-adapter onto the shut-off valve using PTFE tape" },
    { id: "toilets-do-reconnect-cistern", type: "do", text: "Reconnect the existing cistern hose to one port of the T-adapter" },
    { id: "toilets-do-connect-hose", type: "do", text: "Connect the new flexible hose from the second T-adapter port" },
    { id: "toilets-do-drill-bracket", type: "do", text: "Mark and drill bracket position on the wall at a comfortable reachable height" },
    { id: "toilets-do-fix-bracket", type: "do", text: "Fix the wall bracket securely using appropriate plugs and screws" },
    { id: "toilets-do-attach-holder", type: "do", text: "Attach the hand faucet holder to the bracket" },
    { id: "toilets-do-paper-mounts", type: "do", text: "Install toilet paper mounts at comfortable reach height" },
    { id: "toilets-do-connect-faucet", type: "do", text: "Connect the flexible hose to the hand faucet" },
    { id: "toilets-do-turn-on", type: "do", text: "Turn water supply back on and check all joints for leaks" },
    { id: "toilets-do-test-faucet", type: "do", text: "Test the hand faucet and adjust flow if necessary" },
  ],
};
